### ISSUE TITLE
uptime metric wrong

### ISSUE THREAD

**Issue by kevinkk525** [anclrii/Storj-Exporter-dashboard#11]
You are using this for uptime: 100 - avg(storj_sat_uptime{type="score",instance=~"$node.*"}) by(url) * 100
But the metric storj_sat_uptime is the old uptime tracking system that got shut down. Therefore it is always at 100% with your formula, for all my nodes for the past 2 months despite lots of downtime.
The metric you'll want is: avg(storj_sat_summary{type="onlineScore"}) by(instance) * 100

**Comment by anclrii** [comment]
Cool thanks, I'll update the dashboard.
