### ISSUE TITLE
sat_uptime in audit avg score

### ISSUE THREAD

**Issue by kevinkk525** [anclrii/Storj-Exporter-dashboard#2]
You accidentally used the sat_uptime in the audit avg score.

![grafik](https://user-images.githubusercontent.com/9607123/66731165-3678df00-ee56-11e9-9496-66614b6e23d3.png)

**Comment by anclrii** [comment]
Thanks! that's merged now.
Do you think the thresholds I set for these scores are a bit too harsh? 

I'm not sure how low the score can drop before we can start worrying. This should be a point when these guages go yellow. Then go red when it's definitely in trouble.

**Comment by kevinkk525** [comment]
I am not sure about that myself at the moment.
Yesterday I opened a thread about the uptime score: https://forum.storj.io/t/uptime-dropping-considerable-after-server-restart/2216
It just drops too much when doing a simple restart and my big node gets below the accepted uptime score even though it had 0.999999 before the restart. The last uptime did make it drop again. It recovers from that rather quickly so I assume the uptime calculations are done using a very small timeframe:
![grafik](https://user-images.githubusercontent.com/9607123/66743515-6043fd00-ee7a-11e9-9b52-82ee10fc2a27.png)
It takes around 4h to recover 1% uptime score while it is low and less the higher you get but a simple restart during the uptime took 2% from the score and it took at most 20 minutes (that's the gap in prometheus but with scraping every 5 minutes it could be as low as 11 minutes but even that must be due to the starting load of the container itself).

So as long as the uptime score is this wildly fluctuating and we don't have a good answer from STORJ, I can't think of reasonable ranges for the gui.

As for the audit score range: I can't say anything about that, all my nodes have 100%. At the moment you get disqualified at 60% as far as I remember but that's already a very bad value and they will surely change that as soon as the problems with auditing deleted/not uploaded pieces is fixed.

**Comment by kevinkk525** [comment]
Also check the thread because of differences between the uptime and audit score shown in the dashboard and the exposed score in the API.

**Comment by anclrii** [comment]
Ok thanks, I guess we're on the same page then. Will need to wait until score mechanics is clarified. For now the dashboard will highlight if there's any unexpected outage, and the fact that it recovers quickly also helps.
