### ISSUE TITLE
Customize dashboard 

### ISSUE THREAD

**Issue by ayaseen** [anclrii/Storj-Exporter-dashboard#4]
Hello,

This is not an issues, it a little bit about enhance and customize the dashboard specially for node status to use plotstat panel when you have 6 or more nodes.

Thanks

**Comment by anclrii** [comment]
Hi, yes I agree currently the dashboard will not scale to large number of nodes. Which one is node status though? Do you suggest to use a specific plugin for visualisation? Please share more details.

In general I'd like to avoid using non-default grafana plugins at least for now. I'm not sure I'm happy with current visualisation and items represented on the board so I want to allow some time to better understand what's relevant for SNs and how best to represent it. Say I find `Net IO/sum per node monthly` quite useful but not sure if io/sum are doing well on one graph. And then `Audit/Repair IO/sum per node monthly` is doing the job but is it really useful? What do you think?

**Comment by ayaseen** [comment]
Well, I think they have plot panel that can use to represent many nodes .

I am.not sure in your last question these fields are required or not.

Thanks

**Comment by anclrii** [comment]
Hi @ayaseen, I found there's [Boom table plugin](https://grafana.com/grafana/plugins/yesoreyeram-boomtable-panel) that may be useful with many nodes.
Can you try this please https://github.com/anclrii/Storj-Exporter-dashboard/blob/master/Storj-Exporter-Boom-Table.json 
Let me know if it works for you.

**Comment by anclrii** [comment]
looks like this is resolved with Storj-Exporter-Boom-Table.json
